In [2]:
import numpy as np
import pandas as pd

In [3]:
df =pd.read_csv(r"D:\HealthCare Project\Data\Raw Data\healthcare_analytics_100k.csv")

In [5]:
df.head()

,encounter_id,patient_id,admission_date,discharge_date,age,gender,city,blood_type,department,diagnosis,...,billing_amount_inr,test_result,readmission_within_30_days,bmi,heart_rate_bpm,systolic_bp_mmhg,diastolic_bp_mmhg,glucose_mg_dl,total_cholesterol_mg_dl,patient_satisfaction_score
0,ENC00086156,PT0033248,2024-09-17,2024-09-21,59.0,Male,Mumbai,A+,General Medicine,Dehydration,...,17148.82,Abnormal,No,19.7,102.0,115.0,NaN,90.5,155.5,5.0
1,ENC00029634,PT0000126,2025-11-04,2025-11-13,NaN,Male,Aurangabad,O+,Cardiology,Arrhythmia,...,22872.02,Not performed,No,22.4,77.0,135.0,NaN,89.7,NaN,4.0
2,ENC00067711,PT0019308,2025-10-09,2025-10-13,89.0,Male,Other,O+,Neurology,Migraine,...,15707.25,Not performed,No,23.1,103.0,114.0,NaN,NaN,168.5,3.0
3,ENC00062349,PT0037054,2026-05-24,2026-05-26,63.0,Female,Nashik,NaN,Orthopedics,Joint Injury,...,12435.79,Not performed,Yes,24.4,83.0,142.0,69.0,122.3,151.4,5.0
4,ENC00098788,PT0053023,2025-11-14,2025-11-19,90.0,Male,Mumbai,B+,Oncology,Lung Cancer,...,40275.43,Normal,Yes,30.0,68.0,123.0,88.0,271.1,144.7,5.0

#Data Types

In [6]:
df.shape

(100000, 24)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   encounter_id                100000 non-null  str
 1   patient_id                  100000 non-null  str
 2   admission_date              100000 non-null  str
 3   discharge_date              100000 non-null  str
 4   age                         98517 non-null   float64
 5   gender                      99062 non-null   str
 6   city                        100000 non-null  str
 7   blood_type                  87920 non-null   str
 8   department                  100000 non-null  str
 9   diagnosis                   100000 non-null  str
 10  treatment_type              100000 non-null  str
 11  admission_type              100000 non-null  str
 12  insurance_type              92967 non-null   str
 13  length_of_stay_days         100000 non-null  int64
 14  billing_amount_inr          100000 non-null  float64
 15  test_result                 93955 non-null   str
 16  readmission_within_30_days  97457 non-null   str
 17  bmi                         91929 non-null   float64
 18  heart_rate_bpm              95941 non-null   float64
 19  systolic_bp_mmhg            96007 non-null   float64
 20  diastolic_bp_mmhg           96030 non-null   float64
 21  glucose_mg_dl               89821 non-null   float64
 22  total_cholesterol_mg_dl     88932 non-null   float64
 23  patient_satisfaction_score  86002 non-null   float64
dtypes: float64(9), int64(1), str(14)
memory usage: 29.2 MB

In [8]:
df.dtypes

encounter_id                      str
patient_id                        str
admission_date                    str
discharge_date                    str
age                           float64
gender                            str
city                              str
blood_type                        str
department                        str
diagnosis                         str
treatment_type                    str
admission_type                    str
insurance_type                    str
length_of_stay_days             int64
billing_amount_inr            float64
test_result                       str
readmission_within_30_days        str
bmi                           float64
heart_rate_bpm                float64
systolic_bp_mmhg              float64
diastolic_bp_mmhg             float64
glucose_mg_dl                 float64
total_cholesterol_mg_dl       float64
patient_satisfaction_score    float64
dtype: object

In [9]:
df.describe()

,age,length_of_stay_days,billing_amount_inr,bmi,heart_rate_bpm,systolic_bp_mmhg,diastolic_bp_mmhg,glucose_mg_dl,total_cholesterol_mg_dl,patient_satisfaction_score
count,98517.000000,100000.000000,100000.000000,91929.000000,95941.000000,96007.000000,96030.000000,89821.000000,88932.000000,86002.000000
mean,48.931210,4.996690,23489.724548,27.026899,82.049676,126.155062,78.984682,122.326957,192.138836,3.879294
std,20.718747,2.849224,12986.622880,5.166555,13.952155,18.903143,12.003650,53.528451,37.982414,1.088432
min,0.000000,1.000000,500.000000,14.000000,38.000000,75.000000,40.000000,45.000000,80.000000,1.000000
25%,35.000000,3.000000,14338.397500,23.500000,73.000000,113.000000,71.000000,84.200000,166.500000,3.000000
50%,49.000000,4.000000,20849.650000,27.000000,82.000000,126.000000,79.000000,112.000000,192.100000,4.000000
75%,63.000000,6.000000,29898.312500,30.500000,91.000000,139.000000,87.000000,148.700000,217.700000,5.000000
max,100.000000,30.000000,141841.320000,51.000000,135.000000,212.000000,127.000000,500.000000,354.300000,5.000000

### Handle Missing Values

In [10]:
df.isnull().sum()

encounter_id                      0
patient_id                        0
admission_date                    0
discharge_date                    0
age                            1483
gender                          938
city                              0
blood_type                    12080
department                        0
diagnosis                         0
treatment_type                    0
admission_type                    0
insurance_type                 7033
length_of_stay_days               0
billing_amount_inr                0
test_result                    6045
readmission_within_30_days     2543
bmi                            8071
heart_rate_bpm                 4059
systolic_bp_mmhg               3993
diastolic_bp_mmhg              3970
glucose_mg_dl                 10179
total_cholesterol_mg_dl       11068
patient_satisfaction_score    13998
dtype: int64

### Data Cleaning

In [11]:
df['age'] =df['age'].median()
df['gender'] = df['gender'].fillna("Unknown")
df['blood_type'] =df['blood_type'].fillna("Unknown")
df['insurance_type']=df['insurance_type'].fillna("Unknown")
df['test_result']=df['test_result'].fillna("Unknown")
df['readmission_within_30_days']=df['readmission_within_30_days'].fillna("NA")
df['bmi']=df['bmi'].mean()
df['heart_rate_bpm']=df['heart_rate_bpm'].mean()
df['systolic_bp_mmhg']=df['systolic_bp_mmhg'].mean()
df['diastolic_bp_mmhg']=df['diastolic_bp_mmhg'].mean()
df['glucose_mg_dl']=df['glucose_mg_dl'].mean()
df['total_cholesterol_mg_dl']=df['total_cholesterol_mg_dl'].mean()
df['patient_satisfaction_score']=df['patient_satisfaction_score'].mean()

In [12]:
df.isnull().sum()

encounter_id                  0
patient_id                    0
admission_date                0
discharge_date                0
age                           0
gender                        0
city                          0
blood_type                    0
department                    0
diagnosis                     0
treatment_type                0
admission_type                0
insurance_type                0
length_of_stay_days           0
billing_amount_inr            0
test_result                   0
readmission_within_30_days    0
bmi                           0
heart_rate_bpm                0
systolic_bp_mmhg              0
diastolic_bp_mmhg             0
glucose_mg_dl                 0
total_cholesterol_mg_dl       0
patient_satisfaction_score    0
dtype: int64

In [13]:
df.to_csv(r"D:\HealthCare Project\Python\Data Cleaning.csv")